### ISSUE TITLE
Rework technology and item icons

### ISSUE THREAD

**Issue by Fragjacker** [Fragjacker/se-space-trains#3]
# Task

- [x] Create new icon for the Space train technology
- [x] Create a new icon for the Space Locomotive
- [x] Create a new icon for the Space Cargo Wagon
- [x] Create a new icon for the Space Fluid Wagon

# Description
Currently many icons are just placeholders, taken from the Krastorio 2 mod.
