### ISSUE TITLE
Implement proper mod itneroperability between vanilla Krastorio 2 and Space Exploration

### ISSUE THREAD

**Issue by Fragjacker** [Fragjacker/se-space-trains#4]
# Todo

- [x] Add vanilla compatbility.
- [x] Add compatibility with Krastorio 2
- [x] Add compatibility with Space Exploration

# Description
Since different mods offer different ingredients and tech chains, they must be taken care of.
